server {
    listen 8080;
    server_name _;

    location /health {
        return 200 "ok\n";
    }

    location / {
        proxy_pass https://jian.jiandin.com/;
        proxy_ssl_server_name on;

        # 给CF用，访问源站必须填源站host，保证页面正常返回
        proxy_set_header Host jian.jiandin.com;

        # 新增：把浏览器真实访问的代理域名，自定义头传给后端PHP
        proxy_set_header X‑Forwarded‑Host $host;

        proxy_set_header X‑Real‑IP $remote_addr;
        proxy_set_header X‑Forwarded‑For $proxy_add_x_forwarded_for;
        proxy_set_header X‑Forwarded‑Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
