server {
    listen 8080;
    server_name _;

    location /health {
        return 200 "ok\n";
    }

    location / {
        proxy_pass https://jian.jiandin.com/;
        proxy_ssl_server_name on;

        proxy_set_header Host jian.jiandin.com;
        proxy_set_header X‑Real‑IP $remote_addr;
        proxy_set_header X‑Forwarded‑For $proxy_add_x_forwarded_for;
        proxy_set_header X‑Forwarded‑Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        proxy_set_header Accept-Encoding "";
        proxy_redirect https://jian.jiandin.com/ $scheme://$host/;

        sub_filter_types *;
        sub_filter 'https://jian.jiandin.com' '$scheme://$host';
        sub_filter_once off;

        # 尽量放最头部，优先执行劫持脚本
        sub_filter '<head>' '<head><script>(function(){const oriReplace=window.location.replace;const oriAssign=window.location.assign;function fixUrl(u){u=String(u);return u.replace(/https:\/\/jian\.jiandin\.com/gi,window.location.origin);}Object.defineProperty(window,"location",{set:function(v){window.location.href=fixUrl(v);}});window.location.replace=function(u){oriReplace.call(window.location,fixUrl(u));};window.location.assign=function(u){oriAssign.call(window.location,fixUrl(u));};})();</script>';
    }
}
